# Generated by Django 4.2.6 on 2023-11-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='complexion',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='extra',
            field=models.CharField(blank=True, default=None, max_length=4094, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='person',
            name='marital_status',
            field=models.CharField(blank=True, default='Single', max_length=256),
        ),
    ]
