# Generated by Django 4.2.6 on 2023-11-02 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personemotion',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
