# Generated by Django 4.2.6 on 2023-10-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_active_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
